export enum PageNames {
	HOME = 'home',
	HEATINGCOOLING = 'heatingAndCooling',
	ELECTRICAL = 'electrical',
	PLUMBING = 'plumbing',
	ABOUTUS = 'aboutUs',
	FINANCING = 'financing',
	MEMBERSHIPS = 'memberships',
	BLOG = 'blog',
	BLOGPOST = 'blogPost',
	CAREERS = 'careers',
	CONTACTUS = 'contactUs',
	HEADER = 'header',
	FOOTER = 'footer',
	BOOKNOW = 'bookNow',
	MASSSAVE = 'massSave',
	PRIVACYPOLICY = 'privacyPolicy',
	UNDERCONSTRUCTION = 'underConstruction',
	JOBAPPLICATION = 'jobApplication',
}
